[hr]
  languageName = "Hrvatski"
  contentDir = "content/hr"
  weight = 10
  [hr.params]
    languageISO = "HR"
    footer = "Napravljeno sa ❤️ koristeći <a href=\"https://gohugo.io/\">Hugo</a> i <a href=\"https://gohugo.io/\">Doks</a>"


[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    footer = "Made with ❤️ using <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://gohugo.io/\">Doks</a>"

[de]
  languageName = "Deutsch"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "DE"
    footer = "Hergestellt mit ❤️ unter Verwendung von <a href=\"https://gohugo.io/\">Hugo</a> und <a href=\"https://gohugo.io/\">Doks</a>"